### ISSUE TITLE
Add a Prometheus ServiceMonitor to the FluentBit chart

### ISSUE THREAD

**Issue by itay-grudev** [coralogix/telemetry-shippers#140]
The official `FlientBit` chart has a `ServiceMonitor` [(here)](https://github.com/fluent/helm-charts/blob/main/charts/fluent-bit/values.yaml#L96). Could you incorporate it here?

Or even better - fork that chart and just add your logging plugin. It will be easier to maintain and we'll get all of the official extras.

**Comment by amit-mazor** [comment]
We have a serviceMonitor for Fluentbit, its enabled by default, see: 
https://github.com/coralogix/telemetry-shippers/blob/master/logs/fluent-bit/k8s-helm/http/values.yaml#L8

**Comment by itay-grudev** [comment]
@amit-mazor You are absolutely right. I have no idea what I was looking at.
