### ISSUE TITLE
Automate Releases

### ISSUE THREAD

**Issue by ArthurSens** [coralogix/telemetry-shippers#214]
Today we're updating versions and releasing everything manually.

We want to get to a state similar to what https://github.com/open-telemetry/opentelemetry-helm-charts is doing. Automated releases where separate helm charts have separate release tags.

**Comment by matej-g** [comment]
Looks like I simultaneously put https://github.com/coralogix/telemetry-shippers/issues/216 with a bit more details, shall we close this one in favor of that one?

**Comment by ArthurSens** [comment]
yep!
